### PR TITLE
Revert "Added my name to contributer list"

### PR DESCRIPTION
**Pull request by Divya-Vernekar**
Reverts zero-to-mastery/start-here-guidelines#22800

### CODE REVIEW

**Comment by Divya-Vernekar** [comment]
added to contributer list

**Comment by sophiabrandt** [comment]
@Divya-Vernekar why revert?

**Review by suhaanigurjar — CHANGES_REQUESTED** [review]
There was a note to avoid adding yourself at the top or the bottom of the list. Should've followed that to avoid merge issues..

**Comment by suhaanigurjar** [comment]
You could close this PR, and re try by adding your name to the middle of the list instead to avoid any conflicts and have a successful PR merge. Cheers!

**Comment by sophiabrandt** [comment]
I will close this PR.

**Pull request closed without merging**
