### PR TITLE
Test

### PR DESCRIPTION
**Pull request by noufanelachola**
I've tried to add my name to end of the file . @aneagoie @sophiabrandt

### CODE REVIEW

**Comment by noufanelachola** [comment]
Can you send the link to join the github organisation

**Comment by l-white** [comment]
@noufanelachola Which ZTM Github organization are you trying to join? You are welcome to contribute to any of the open-source projects that are not archived.

**Comment by noufanelachola** [comment]
Hi there,

Let me begin with thanking you for giving me a early reply .

I meant that am unable to show the ztm icon under the organisation section
in my github profile due to I got no any invite links to join .

Looking forward to hearing from you.

Regards
Noufan

**Comment by l-white** [comment]
@noufanelachola Hi Noufan, These instructions from Github might be helpful to you. https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile

**Pull request merged**
