### PR TITLE
added my name to the contributor list

### PR DESCRIPTION
**Pull request by MikeDev123**
Added my name to the list

### CODE REVIEW

**Comment by Sharpmind015** [comment]
Nice

**Comment by MikeDev123** [comment]
> Nice

@Sharpmind015 

have a good day :)

**Comment by MikeDev123** [comment]
is there an issue?

Michael Calunsod



On 29 Jun 2020, at 11:57 PM, zero-to-mastery-bot[bot] <notifications@github.com> wrote:

﻿

⚠️ MERGE CONFLICT DETECTED!

@MikeDev123<https://github.com/MikeDev123> A possible conflict has been detected, you will need to resolve this before your pull request can be merged. The most common reason conflicts occur, is when the contributor does not run git pull origin master before pushing their new changes.

Before we can merge the code, you will need to resolve the conflict, there are tons of guides on Google and Youtube to help you out. If you get stuck ask over on Discord.

**Comment by sophiabrandt** [comment]
@MikeDev123 yes. This repository is _extremely_ active and might change every few minutes, so it's easy for your fork to be out of sync.
Can you do a `git pull origin master` and merge the updated master branch into your fork? After you've resolved your merge conflicts, you can push again, and we (or ZeroBot) will be able to merge your contribution. Thank you.

**Pull request closed without merging**
