### PR TITLE
Check

### PR DESCRIPTION
**Pull request by hamza-ibrahim**
My first open source PR

### CODE REVIEW

**Comment by DiscoverSquishy** [comment]
I am pretty sure that in order to add yourself you need to have a name without a - or _ but I'm unsure.
Please reopen this once you have changed your username something of your liking excluding a -.

**Comment by hamza-ibrahim** [comment]
I understand the confusion, but that is how my username is written for github and I have come across many of that nature in the list. As they are github usernames that used  '_' and '-':

Such as: 

-@A-Dolah

-@Z-69


@DiscoverSquishy

**Comment by DiscoverSquishy** [comment]
Strange, I’m not compelty sure what’s causing the conflict error. Gonna pass this to @MattCSmith.

**Comment by MattCSmith** [comment]
@hamza-ibrahim @DiscoverSquishy 
The markup/code looks fine to me. I can not see the conflict details since the PR is closed. However it is most likely a result of pushing without pull the most recent updates. Eg. your push will overwrite someone else recent changes.

**Comment by hamza-ibrahim** [comment]
@DiscoverSquishy  @MattCSmith 

Hi there, thing was I could not reopen the PR after @DiscoverSquishy closed it. So instead I created another PR and hence this is causing a problem (that PR was successfully merged). I deleted both branches since.

Sorry for the time and hassle, thanks for trying to help out either way.

**Pull request closed without merging**
