### PR TITLE
I have organized the contributor list to a more uniform one

### PR DESCRIPTION
**Pull request by cardonaw**
When added my name, I saw that the contributors list was not uniform. I fixed the little syntax errors, so its prettier now @aneagoie

### CODE REVIEW

**Comment by cardonaw** [comment]
I have to say that I didn't delete anyone from the list, just wanted to help

**Comment by donmarvex** [comment]
@ZMonk91 has implemented something in the sort-users.py file but the CI action doesn't get run as stated in this issue here #15873 
A few contributions will always change some formatting as evidenced from the past and every now and then manual fixes are implemented but for the sake of avoiding repititive fixes, we should focus on trying to solve the issue. If you have any ideas, they are welcome!

**Comment by cardonaw** [comment]
oh! I see. I'll check this later and if I find something useful to fix it, I'll let you know

**Comment by donmarvex** [comment]
> oh! I see. I'll check this later and if I find something useful to fix it, I'll let you know

@cardonaw That would be great!

**Pull request closed without merging**
