### PR TITLE
added my name to the contributors list.

### PR DESCRIPTION
**Pull request by mitinull**
Cool!

### CODE REVIEW

**Comment by mitinull** [comment]
I didn't get the "Pull shark" achievement😭. Why is that? Is there a way I can get it? @aneagoie

**Comment by mitinull** [comment]
I think I got it.🙃 It seems I have to make a second pull request to get the badge.

**Comment by l-white** [comment]
@mitinull Nice job!

**Comment by mitinull** [comment]
@l-white Thanks!

**Pull request merged**
