### PR TITLE
Adding my name after reset

### PR DESCRIPTION
**Pull request by aunhengly**
This is the second attempt to add my name to the list.

### CODE REVIEW

**Comment by aunhengly** [comment]
Hi there,
anybody can help me to resolve the conflicts, please.
I am trying to reset and redo everything but still in conflict.

**Comment by Milan-960** [comment]
> Hi there,
> 
> anybody can help me to resolve the conflicts, please.
> 
> I am trying to reset and redo everything but still in conflict.

Yes! The thing which you need to do is before resetting anything first run "git pull" on your master branch after that you should make changes and push that branch on your repository!

**Comment by aunhengly** [comment]
Hi Milan,
Thanks for your feedback. I did the git pull:
"git remote add upstream https://github.com/zero-to-mastery/start-here-guidelines.git
git pull upstream master".
And add, commit, and push already.

How do I know the conflict is resolved? I didn't see my name on the list yet, is it mean I still have the conflict?
Thanks,

**Comment by Milan-960** [comment]
Hey,

No problem! Well I think you should try to fork the repo again in your account and follow all the commands one by one! 

Add your name in to list and push it to your master branch :) and create a new pull request after that it will not show any conflict! 

Yes you are not able to see in ZTM repo because they didn't merge your branch yet so..

**Comment by aunhengly** [comment]
Hi Milan,
Great and thanks, now there is no conflict, but I didn't see my name on the list yet. Is it something usual or do I have to wait for you or a team member to merge it?

Thanks,

**Comment by Milan-960** [comment]
Hey,

Yes as I said your branch has not been merged yet that's why you won't be able to see your name in ZTM repository! Yes you will have to wait until they do not merge the branch :) even I do not have an access to do that so.. 

No problem at all,
Have great day.

**Pull request merged**
