### PR TITLE
adding my name to the list

### PR DESCRIPTION
**Pull request by excel61**
just added myself to the list. Please let me in

### CODE REVIEW

**Comment by excel61** [comment]
I did everything just like what the teacher said, but in my case it shows a conflict. can you explain what's wrong?

**Comment by SamirJouni** [comment]
Sure ! 
I can't remember if Andrei said this in the lecture but you need to update your fork before you push changes to it so that you don't get any conflicts.

Conflicts happen when you have written code on.. say for example line 20. And for you on your fork line 20 was empty prior to writing code there. But on the original repo, line 20 was already occupied by other code. 
So when git or github see this, they basically decide that there are conflicting lines and you have to decide whether to keep both and where to position each. The conflicting lines are usually between conflict markers. I'm sure you've seen conflict markers in the lecture, so you know what they look like.

**Comment by SamirJouni** [comment]
opera snapshot_2018-10-30_143034_github com
opera snapshot_2018-10-30_143127_github com

If you look at both images, one shows the conflict markers... so the lines that are conflicting with your line. And then in the other image I had fixed it, and that's what it's supposed to look like. Since these other people have added their names before you did, but you didn't update your fork with those changes. :)

**Comment by excel61** [comment]
Thank's a lot, I really appreciate your help but, when you say "I need to update my fork",  do you mean  syncing ($ git remote -v command)  or pulling ($ git pull command) ?

**Pull request merged**
