### PR TITLE
Added my name to contributor list

### PR DESCRIPTION
**Pull request by Stefan3002**
Hey, I have added my name here as part of the ZTM tutorial from the React Course on Udemy. Cheers!

### CODE REVIEW

**Comment by l-white** [comment]
@Stefan3002 Nice job! Keep up the good work.

**Comment by Stefan3002** [comment]
> @Stefan3002 Nice job! Keep up the good work.

Thanks a lot. It's really awesome to be part of the ZTM community. Looking forward for even more great courses and resources (I have already completed like 3-4 courses from ZTM).

**Comment by l-white** [comment]
@Stefan3002 You are most welcome! Thank you for being part of the ZTM community. It is students like you who make it great. And nice work on completing several courses already! Keep up the good work, and I look forward to seeing you  in the Discord server.

**Comment by Stefan3002** [comment]
> @Stefan3002 You are most welcome! Thank you for being part of the ZTM community. It is students like you who make it great. And nice work on completing several courses already! Keep up the good work, and I look forward to seeing you in the Discord server.

Actually we did talk in the Discord Server a bit, and I really want to thank you for your continuous support that you offered me there.
This is my Discord profile.
Thanks again and have a great day!

image

**Pull request merged**
