### PR TITLE
added my name to contributors list

### PR DESCRIPTION
**Pull request by kirisutoweb**
Just added my name to the contributors list. @r4pt0s

### CODE REVIEW

**Comment by kirisutoweb** [comment]
Hello I added my name to the contributors list yesterday. Could you accept? Thank you.

**Comment by kirisutoweb** [comment]
hello @sophiabrandt, please I dont understand why I see now the conflict label on my request. Please can you explain it to me. I thought I resolved the conflict.

**Comment by kirisutoweb** [comment]
> hello @sophiabrandt, please I dont understand why I see now the conflict label on my request. Please can you explain it to me. I thought I resolved the conflict.

**Comment by sophiabrandt** [comment]
There are new conflicts happening when other pull requests were merged.

Unfortunately, I don't have the time to always fix these merge conflicts myself.

While this is a bit unfortunate, there are only 2 ways going forward right now:

a) you can fix these merge conflicts (as you have done before, please don't forget to sync your fork (https://short.pm/forksync)
b) close this pull request, and make a new one with the current state of the repository
c) as this was probably just an exercise for you, forgo this contribution and put effort in other tasks/other open-source-projects

Matt from the ZTM team is working on a better way to avoid these type of conflicts in the future.

Thank you for your time.

**Comment by kirisutoweb** [comment]
> There are new conflicts happening when other pull requests were merged.
> 
> Unfortunately, I don't have the time to always fix these merge conflicts myself.
> 
> While this is a bit unfortunate, there are only 2 ways going forward right now:
> 
> a) you can fix these merge conflicts (as you have done before, please don't forget to sync your fork (https://short.pm/forksync) b) close this pull request, and make a new one with the current state of the repository c) as this was probably just an exercise for you, forgo this contribution and put effort in other tasks/other open-source-projects
> 
> Matt from the ZTM team is working on a better way to avoid these type of conflicts in the future.
> 
> Thank you for your time.

Hello @sophiabrandt Thank you for you Reply. It's very appreciated.

**Pull request merged**
