### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by mattevenkateswarlu**
I added my GitHub account to join ZTM community

### CODE REVIEW

**Comment by mattevenkateswarlu** [comment]
On Sun, Apr 2, 2023 at 7:26 AM stale[bot] ***@***.***> wrote

Hai I am unable to login my login details can u please help me ! Thanks !

**Comment by l-white** [comment]
@mattevenkateswarlu What are you trying to login to?

**Comment by mattevenkateswarlu** [comment]
I am trying to login my username with password to zero to mastery course
where I purchased with using this email ID currently using  but I forget
password I am not getting otp or anything it doesn’t work mail what can I
do so I need suggestions thanks ! I purchase lifetime subscription ! Thanks
!

**Comment by l-white** [comment]
@mattevenkateswarlu If you contact support@zerotomastery.io, they should be able to help you with your subscription issue.

**Pull request closed without merging**
