### PR TITLE
added my name to contributor list

### PR DESCRIPTION
**Pull request by TimothyRowland**
I've added my name to the list.

### CODE REVIEW

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Please remove the `.vs` folder from your pull request. Thank you.

**Comment by TimothyRowland** [comment]
I've removed the file as requested.

**Comment by sophiabrandt** [comment]
@TimothyRowland thanks, but now you added a different file. Please remove _everything_ except the `CONTRIBUTORS.md` file.

**Comment by TimothyRowland** [comment]
I'm sorry for this headache, but it's not letting me remove any of the files now. I'm assuming I'm doing it incorrectly.

**Comment by sophiabrandt** [comment]
I've added your name manually to avoid committing the `.vs` folder. You should see your name in `CONTRIBUTORS.md`.

**Pull request closed without merging**
