### PR TITLE
"Hello there. Just added myself to the contributors!"

### PR DESCRIPTION
**Pull request by Jrejoire**

### CODE REVIEW

**Comment by LeiAlan** [comment]
I have no rights to add myself as new contributor. Could you help it?

**Comment by Jrejoire** [comment]
Hey @LeiAlan I have no rights either. I'll just wait for the admins to pop in. Have you created a pull request already?

**Comment by LeiAlan** [comment]
Hi @Jrejoire , I just download it using git bash but can't push due to no access right.

**Comment by Jrejoire** [comment]
oh I see. Any admin can help with that?

**Pull request merged**
