### PR TITLE
added my name to contributor list

### PR DESCRIPTION
**Pull request by OlusegunJoseph**
I've added my name to the list.@aneagoie

### CODE REVIEW

**Review by clevermiraz — APPROVED** [review]
Look EveryThing Ok

**Comment by OlusegunJoseph** [comment]
Hello Amin,

Thanks for approving my pull request but still, I cannot find my name in
the contributor list.

**Comment by OlusegunJoseph** [comment]
@clevermiraz has my pull request been merged all you are just suggestion everything looks good?

**Comment by LaurelineP** [comment]
@OlusegunJoseph  it's your merged time 👍 
- no before it was not merged --> the open pill tag here is stating it is still open 
image
Only ZTM team members / mentors can handle the merge requests :) 
-----
image
Now the purple pill here is stating it is now merged :) 

I also confirm your line aggregation is here :) 
Great continuation to you ! 🚀

**Pull request merged**
