### PR TITLE
added username and cleanup

### PR DESCRIPTION
**Pull request by loocd**

### CODE REVIEW

**Comment by loocd** [comment]
Is there a reason, this isn't being merged?

**Comment by sophiabrandt** [comment]
@loocd This PR had merge conflicts but the bot didn't detect them automatically. That's why the bot didn't told you so. There was no indication that you had to do something, _but_ the PR's merge conflicts still had to be resolved by one of the maintainers manually.
My guess is that nobody had time recently, so it slipped through.
I've re-opened the PR.
Next time, if the stale bot tries to close your PR, you can just add a comment if you like. That way there is activity on the repo, so the bot won't close.

**Comment by loocd** [comment]
Thanks for the feedback @sophiabrandt 
Anything I need to do regarding the merge conflict?

**Comment by sophiabrandt** [comment]
@loocd I'll take care of it when I have time. No worries.

**Pull request merged**
