### PR TITLE
Added my name to contributor list

### PR DESCRIPTION
**Pull request by MartinKearney**
Hi - I've added my name to the list :)

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Please fix merge conflict markers.

**Review by MartinKearney — COMMENTED** [review]
Is there a way I can cancel this and start from scratch? I've tried my best...

**Comment by sophiabrandt** [comment]
You could close this PR and start from a clean slate if you like. This might be easier.

**Comment by MartinKearney** [comment]
Ok - will try again from scratch...

**Pull request closed without merging**
