### PR TITLE
Trying this pull again

### PR DESCRIPTION
**Pull request by michael-roq**
Every time somebody submits a name, a new conflict arises before I can merge.

### CODE REVIEW

**Comment by michael-roq** [comment]
I keep getting back the response:     merge: upstream - not something we can merge

**Comment by sophiabrandt** [comment]
Please follow the steps [here](https://short.pm) to synchronize your fork.

**Comment by michael-roq** [comment]
Hi Sophia,

So I accidentally named my origin under the same url as the upstream url,
instead of under my own name.  How do I fix that?

Best,

Michael

**Comment by sophiabrandt** [comment]
@michael-roq you can delete the remote repositories.
Example:
```bash
git remote -v
```
This command should show you all your remotes. One should be _your_ fork (normally called `origin`). The other should be the `upstream` (meaning _this_ repository).

You can remove remote repositories:
```bash
git remote remove upstream
```
This should remove whatever was under `upstream`. Then you can follow the steps in the link above.

**Comment by michael-roq** [comment]
Hi Sophia,

Thank you for the help!

Best,

Michael

**Pull request closed without merging**
